software_groups: &software
  - "base"
jobs:
  imagemagick:
    builder: make
    base: "ubuntu:12.04"
    software_groups: *software
    packages:
      - type: debian
        name: imagemagick
        version: "8:6.8.9-1"
        depends: 
          - libc6
          - libbz2-1.0
          - libfontconfig1
          - libfreetype6
          - libgomp1
          - libjasper1
          - libjpeg8
          - liblcms1
          - liblqr-1-0
          - libltdl7
          - libpng12-0
          - libtiff4
          - libx11-6
          - libxext6
          - libxml2
          - zlib1g
        target: install
        repos:
          - mxm
